

all: measurement context-switch

clean:
		rm -f measurement context-switch

measurement: measurement.c
		gcc -o measurement measurement.c -Wall

context-switch: context-switch.c
		gcc -o context-switch context-switch.c -Wall

