

all: homework1 homework2 homework3 homework4 homework5 homework6 homework7 homework8

clean:
		rm -f homework1 homework2 homework3 homework4 homework5 homework6 homework7 homework8

homework1: homework1.c
		gcc -o homework1 homework1.c -Wall

homework2: homework2.c
		gcc -o homework2 homework2.c -Wall

homework3: homework3.c
		gcc -o homework3 homework3.c -Wall

homework4: homework4.c
		gcc -o homework4 homework4.c -Wall

homework5: homework5.c
		gcc -o homework5 homework5.c -Wall

homework6: homework6.c
		gcc -o homework6 homework6.c -Wall

homework7: homework7.c
		gcc -o homework7 homework7.c -Wall

homework8: homework8.c
		gcc -o homework8 homework8.c -Wall